import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
// import BookCallButton from '@/components/BookCallButton';
// import FaqButton from '@/components/FaqButton'; // Import the new FaqButton component

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/*<header className="sticky top-0 bg-background/80 backdrop-blur-sm z-50 py-2 border-b">
          <div className="container flex items-center justify-end px-4">
            <FaqButton />
            <BookCallButton />
          </div>
        </header>*/}
        {children}
      </body>
    </html>
  );
}
